
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Telemetry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Telemetry
 * 
 */
export type TelemetryModel = runtime.Types.Result.DefaultSelection<Prisma.$TelemetryPayload>

export type AggregateTelemetry = {
  _count: TelemetryCountAggregateOutputType | null
  _avg: TelemetryAvgAggregateOutputType | null
  _sum: TelemetrySumAggregateOutputType | null
  _min: TelemetryMinAggregateOutputType | null
  _max: TelemetryMaxAggregateOutputType | null
}

export type TelemetryAvgAggregateOutputType = {
  id: number | null
  speed: number | null
  temperature: number | null
  pressure: number | null
  vibration: number | null
  load: number | null
}

export type TelemetrySumAggregateOutputType = {
  id: number | null
  speed: number | null
  temperature: number | null
  pressure: number | null
  vibration: number | null
  load: number | null
}

export type TelemetryMinAggregateOutputType = {
  id: number | null
  speed: number | null
  temperature: number | null
  pressure: number | null
  vibration: number | null
  load: number | null
  createdAt: Date | null
}

export type TelemetryMaxAggregateOutputType = {
  id: number | null
  speed: number | null
  temperature: number | null
  pressure: number | null
  vibration: number | null
  load: number | null
  createdAt: Date | null
}

export type TelemetryCountAggregateOutputType = {
  id: number
  speed: number
  temperature: number
  pressure: number
  vibration: number
  load: number
  createdAt: number
  _all: number
}


export type TelemetryAvgAggregateInputType = {
  id?: true
  speed?: true
  temperature?: true
  pressure?: true
  vibration?: true
  load?: true
}

export type TelemetrySumAggregateInputType = {
  id?: true
  speed?: true
  temperature?: true
  pressure?: true
  vibration?: true
  load?: true
}

export type TelemetryMinAggregateInputType = {
  id?: true
  speed?: true
  temperature?: true
  pressure?: true
  vibration?: true
  load?: true
  createdAt?: true
}

export type TelemetryMaxAggregateInputType = {
  id?: true
  speed?: true
  temperature?: true
  pressure?: true
  vibration?: true
  load?: true
  createdAt?: true
}

export type TelemetryCountAggregateInputType = {
  id?: true
  speed?: true
  temperature?: true
  pressure?: true
  vibration?: true
  load?: true
  createdAt?: true
  _all?: true
}

export type TelemetryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Telemetry to aggregate.
   */
  where?: Prisma.TelemetryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Telemetries to fetch.
   */
  orderBy?: Prisma.TelemetryOrderByWithRelationInput | Prisma.TelemetryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TelemetryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Telemetries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Telemetries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Telemetries
  **/
  _count?: true | TelemetryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TelemetryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TelemetrySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TelemetryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TelemetryMaxAggregateInputType
}

export type GetTelemetryAggregateType<T extends TelemetryAggregateArgs> = {
      [P in keyof T & keyof AggregateTelemetry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTelemetry[P]>
    : Prisma.GetScalarType<T[P], AggregateTelemetry[P]>
}




export type TelemetryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TelemetryWhereInput
  orderBy?: Prisma.TelemetryOrderByWithAggregationInput | Prisma.TelemetryOrderByWithAggregationInput[]
  by: Prisma.TelemetryScalarFieldEnum[] | Prisma.TelemetryScalarFieldEnum
  having?: Prisma.TelemetryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TelemetryCountAggregateInputType | true
  _avg?: TelemetryAvgAggregateInputType
  _sum?: TelemetrySumAggregateInputType
  _min?: TelemetryMinAggregateInputType
  _max?: TelemetryMaxAggregateInputType
}

export type TelemetryGroupByOutputType = {
  id: number
  speed: number
  temperature: number
  pressure: number
  vibration: number
  load: number
  createdAt: Date
  _count: TelemetryCountAggregateOutputType | null
  _avg: TelemetryAvgAggregateOutputType | null
  _sum: TelemetrySumAggregateOutputType | null
  _min: TelemetryMinAggregateOutputType | null
  _max: TelemetryMaxAggregateOutputType | null
}

type GetTelemetryGroupByPayload<T extends TelemetryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TelemetryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TelemetryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TelemetryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TelemetryGroupByOutputType[P]>
      }
    >
  >



export type TelemetryWhereInput = {
  AND?: Prisma.TelemetryWhereInput | Prisma.TelemetryWhereInput[]
  OR?: Prisma.TelemetryWhereInput[]
  NOT?: Prisma.TelemetryWhereInput | Prisma.TelemetryWhereInput[]
  id?: Prisma.IntFilter<"Telemetry"> | number
  speed?: Prisma.IntFilter<"Telemetry"> | number
  temperature?: Prisma.FloatFilter<"Telemetry"> | number
  pressure?: Prisma.FloatFilter<"Telemetry"> | number
  vibration?: Prisma.FloatFilter<"Telemetry"> | number
  load?: Prisma.IntFilter<"Telemetry"> | number
  createdAt?: Prisma.DateTimeFilter<"Telemetry"> | Date | string
}

export type TelemetryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  speed?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  pressure?: Prisma.SortOrder
  vibration?: Prisma.SortOrder
  load?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TelemetryWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TelemetryWhereInput | Prisma.TelemetryWhereInput[]
  OR?: Prisma.TelemetryWhereInput[]
  NOT?: Prisma.TelemetryWhereInput | Prisma.TelemetryWhereInput[]
  speed?: Prisma.IntFilter<"Telemetry"> | number
  temperature?: Prisma.FloatFilter<"Telemetry"> | number
  pressure?: Prisma.FloatFilter<"Telemetry"> | number
  vibration?: Prisma.FloatFilter<"Telemetry"> | number
  load?: Prisma.IntFilter<"Telemetry"> | number
  createdAt?: Prisma.DateTimeFilter<"Telemetry"> | Date | string
}, "id">

export type TelemetryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  speed?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  pressure?: Prisma.SortOrder
  vibration?: Prisma.SortOrder
  load?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TelemetryCountOrderByAggregateInput
  _avg?: Prisma.TelemetryAvgOrderByAggregateInput
  _max?: Prisma.TelemetryMaxOrderByAggregateInput
  _min?: Prisma.TelemetryMinOrderByAggregateInput
  _sum?: Prisma.TelemetrySumOrderByAggregateInput
}

export type TelemetryScalarWhereWithAggregatesInput = {
  AND?: Prisma.TelemetryScalarWhereWithAggregatesInput | Prisma.TelemetryScalarWhereWithAggregatesInput[]
  OR?: Prisma.TelemetryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TelemetryScalarWhereWithAggregatesInput | Prisma.TelemetryScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Telemetry"> | number
  speed?: Prisma.IntWithAggregatesFilter<"Telemetry"> | number
  temperature?: Prisma.FloatWithAggregatesFilter<"Telemetry"> | number
  pressure?: Prisma.FloatWithAggregatesFilter<"Telemetry"> | number
  vibration?: Prisma.FloatWithAggregatesFilter<"Telemetry"> | number
  load?: Prisma.IntWithAggregatesFilter<"Telemetry"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Telemetry"> | Date | string
}

export type TelemetryCreateInput = {
  speed: number
  temperature: number
  pressure: number
  vibration: number
  load: number
  createdAt?: Date | string
}

export type TelemetryUncheckedCreateInput = {
  id?: number
  speed: number
  temperature: number
  pressure: number
  vibration: number
  load: number
  createdAt?: Date | string
}

export type TelemetryUpdateInput = {
  speed?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  pressure?: Prisma.FloatFieldUpdateOperationsInput | number
  vibration?: Prisma.FloatFieldUpdateOperationsInput | number
  load?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TelemetryUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speed?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  pressure?: Prisma.FloatFieldUpdateOperationsInput | number
  vibration?: Prisma.FloatFieldUpdateOperationsInput | number
  load?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TelemetryCreateManyInput = {
  id?: number
  speed: number
  temperature: number
  pressure: number
  vibration: number
  load: number
  createdAt?: Date | string
}

export type TelemetryUpdateManyMutationInput = {
  speed?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  pressure?: Prisma.FloatFieldUpdateOperationsInput | number
  vibration?: Prisma.FloatFieldUpdateOperationsInput | number
  load?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TelemetryUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  speed?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  pressure?: Prisma.FloatFieldUpdateOperationsInput | number
  vibration?: Prisma.FloatFieldUpdateOperationsInput | number
  load?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TelemetryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speed?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  pressure?: Prisma.SortOrder
  vibration?: Prisma.SortOrder
  load?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TelemetryAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speed?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  pressure?: Prisma.SortOrder
  vibration?: Prisma.SortOrder
  load?: Prisma.SortOrder
}

export type TelemetryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speed?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  pressure?: Prisma.SortOrder
  vibration?: Prisma.SortOrder
  load?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TelemetryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speed?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  pressure?: Prisma.SortOrder
  vibration?: Prisma.SortOrder
  load?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TelemetrySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  speed?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  pressure?: Prisma.SortOrder
  vibration?: Prisma.SortOrder
  load?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type TelemetrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  speed?: boolean
  temperature?: boolean
  pressure?: boolean
  vibration?: boolean
  load?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["telemetry"]>

export type TelemetrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  speed?: boolean
  temperature?: boolean
  pressure?: boolean
  vibration?: boolean
  load?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["telemetry"]>

export type TelemetrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  speed?: boolean
  temperature?: boolean
  pressure?: boolean
  vibration?: boolean
  load?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["telemetry"]>

export type TelemetrySelectScalar = {
  id?: boolean
  speed?: boolean
  temperature?: boolean
  pressure?: boolean
  vibration?: boolean
  load?: boolean
  createdAt?: boolean
}

export type TelemetryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "speed" | "temperature" | "pressure" | "vibration" | "load" | "createdAt", ExtArgs["result"]["telemetry"]>

export type $TelemetryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Telemetry"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    speed: number
    temperature: number
    pressure: number
    vibration: number
    load: number
    createdAt: Date
  }, ExtArgs["result"]["telemetry"]>
  composites: {}
}

export type TelemetryGetPayload<S extends boolean | null | undefined | TelemetryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TelemetryPayload, S>

export type TelemetryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TelemetryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TelemetryCountAggregateInputType | true
  }

export interface TelemetryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Telemetry'], meta: { name: 'Telemetry' } }
  /**
   * Find zero or one Telemetry that matches the filter.
   * @param {TelemetryFindUniqueArgs} args - Arguments to find a Telemetry
   * @example
   * // Get one Telemetry
   * const telemetry = await prisma.telemetry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TelemetryFindUniqueArgs>(args: Prisma.SelectSubset<T, TelemetryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Telemetry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TelemetryFindUniqueOrThrowArgs} args - Arguments to find a Telemetry
   * @example
   * // Get one Telemetry
   * const telemetry = await prisma.telemetry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TelemetryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TelemetryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Telemetry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TelemetryFindFirstArgs} args - Arguments to find a Telemetry
   * @example
   * // Get one Telemetry
   * const telemetry = await prisma.telemetry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TelemetryFindFirstArgs>(args?: Prisma.SelectSubset<T, TelemetryFindFirstArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Telemetry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TelemetryFindFirstOrThrowArgs} args - Arguments to find a Telemetry
   * @example
   * // Get one Telemetry
   * const telemetry = await prisma.telemetry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TelemetryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TelemetryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Telemetries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TelemetryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Telemetries
   * const telemetries = await prisma.telemetry.findMany()
   * 
   * // Get first 10 Telemetries
   * const telemetries = await prisma.telemetry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const telemetryWithIdOnly = await prisma.telemetry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TelemetryFindManyArgs>(args?: Prisma.SelectSubset<T, TelemetryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Telemetry.
   * @param {TelemetryCreateArgs} args - Arguments to create a Telemetry.
   * @example
   * // Create one Telemetry
   * const Telemetry = await prisma.telemetry.create({
   *   data: {
   *     // ... data to create a Telemetry
   *   }
   * })
   * 
   */
  create<T extends TelemetryCreateArgs>(args: Prisma.SelectSubset<T, TelemetryCreateArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Telemetries.
   * @param {TelemetryCreateManyArgs} args - Arguments to create many Telemetries.
   * @example
   * // Create many Telemetries
   * const telemetry = await prisma.telemetry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TelemetryCreateManyArgs>(args?: Prisma.SelectSubset<T, TelemetryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Telemetries and returns the data saved in the database.
   * @param {TelemetryCreateManyAndReturnArgs} args - Arguments to create many Telemetries.
   * @example
   * // Create many Telemetries
   * const telemetry = await prisma.telemetry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Telemetries and only return the `id`
   * const telemetryWithIdOnly = await prisma.telemetry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TelemetryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TelemetryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Telemetry.
   * @param {TelemetryDeleteArgs} args - Arguments to delete one Telemetry.
   * @example
   * // Delete one Telemetry
   * const Telemetry = await prisma.telemetry.delete({
   *   where: {
   *     // ... filter to delete one Telemetry
   *   }
   * })
   * 
   */
  delete<T extends TelemetryDeleteArgs>(args: Prisma.SelectSubset<T, TelemetryDeleteArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Telemetry.
   * @param {TelemetryUpdateArgs} args - Arguments to update one Telemetry.
   * @example
   * // Update one Telemetry
   * const telemetry = await prisma.telemetry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TelemetryUpdateArgs>(args: Prisma.SelectSubset<T, TelemetryUpdateArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Telemetries.
   * @param {TelemetryDeleteManyArgs} args - Arguments to filter Telemetries to delete.
   * @example
   * // Delete a few Telemetries
   * const { count } = await prisma.telemetry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TelemetryDeleteManyArgs>(args?: Prisma.SelectSubset<T, TelemetryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Telemetries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TelemetryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Telemetries
   * const telemetry = await prisma.telemetry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TelemetryUpdateManyArgs>(args: Prisma.SelectSubset<T, TelemetryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Telemetries and returns the data updated in the database.
   * @param {TelemetryUpdateManyAndReturnArgs} args - Arguments to update many Telemetries.
   * @example
   * // Update many Telemetries
   * const telemetry = await prisma.telemetry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Telemetries and only return the `id`
   * const telemetryWithIdOnly = await prisma.telemetry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TelemetryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TelemetryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Telemetry.
   * @param {TelemetryUpsertArgs} args - Arguments to update or create a Telemetry.
   * @example
   * // Update or create a Telemetry
   * const telemetry = await prisma.telemetry.upsert({
   *   create: {
   *     // ... data to create a Telemetry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Telemetry we want to update
   *   }
   * })
   */
  upsert<T extends TelemetryUpsertArgs>(args: Prisma.SelectSubset<T, TelemetryUpsertArgs<ExtArgs>>): Prisma.Prisma__TelemetryClient<runtime.Types.Result.GetResult<Prisma.$TelemetryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Telemetries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TelemetryCountArgs} args - Arguments to filter Telemetries to count.
   * @example
   * // Count the number of Telemetries
   * const count = await prisma.telemetry.count({
   *   where: {
   *     // ... the filter for the Telemetries we want to count
   *   }
   * })
  **/
  count<T extends TelemetryCountArgs>(
    args?: Prisma.Subset<T, TelemetryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TelemetryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Telemetry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TelemetryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TelemetryAggregateArgs>(args: Prisma.Subset<T, TelemetryAggregateArgs>): Prisma.PrismaPromise<GetTelemetryAggregateType<T>>

  /**
   * Group by Telemetry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TelemetryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TelemetryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TelemetryGroupByArgs['orderBy'] }
      : { orderBy?: TelemetryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TelemetryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTelemetryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Telemetry model
 */
readonly fields: TelemetryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Telemetry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TelemetryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Telemetry model
 */
export interface TelemetryFieldRefs {
  readonly id: Prisma.FieldRef<"Telemetry", 'Int'>
  readonly speed: Prisma.FieldRef<"Telemetry", 'Int'>
  readonly temperature: Prisma.FieldRef<"Telemetry", 'Float'>
  readonly pressure: Prisma.FieldRef<"Telemetry", 'Float'>
  readonly vibration: Prisma.FieldRef<"Telemetry", 'Float'>
  readonly load: Prisma.FieldRef<"Telemetry", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Telemetry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Telemetry findUnique
 */
export type TelemetryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * Filter, which Telemetry to fetch.
   */
  where: Prisma.TelemetryWhereUniqueInput
}

/**
 * Telemetry findUniqueOrThrow
 */
export type TelemetryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * Filter, which Telemetry to fetch.
   */
  where: Prisma.TelemetryWhereUniqueInput
}

/**
 * Telemetry findFirst
 */
export type TelemetryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * Filter, which Telemetry to fetch.
   */
  where?: Prisma.TelemetryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Telemetries to fetch.
   */
  orderBy?: Prisma.TelemetryOrderByWithRelationInput | Prisma.TelemetryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Telemetries.
   */
  cursor?: Prisma.TelemetryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Telemetries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Telemetries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Telemetries.
   */
  distinct?: Prisma.TelemetryScalarFieldEnum | Prisma.TelemetryScalarFieldEnum[]
}

/**
 * Telemetry findFirstOrThrow
 */
export type TelemetryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * Filter, which Telemetry to fetch.
   */
  where?: Prisma.TelemetryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Telemetries to fetch.
   */
  orderBy?: Prisma.TelemetryOrderByWithRelationInput | Prisma.TelemetryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Telemetries.
   */
  cursor?: Prisma.TelemetryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Telemetries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Telemetries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Telemetries.
   */
  distinct?: Prisma.TelemetryScalarFieldEnum | Prisma.TelemetryScalarFieldEnum[]
}

/**
 * Telemetry findMany
 */
export type TelemetryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * Filter, which Telemetries to fetch.
   */
  where?: Prisma.TelemetryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Telemetries to fetch.
   */
  orderBy?: Prisma.TelemetryOrderByWithRelationInput | Prisma.TelemetryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Telemetries.
   */
  cursor?: Prisma.TelemetryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Telemetries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Telemetries.
   */
  skip?: number
  distinct?: Prisma.TelemetryScalarFieldEnum | Prisma.TelemetryScalarFieldEnum[]
}

/**
 * Telemetry create
 */
export type TelemetryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * The data needed to create a Telemetry.
   */
  data: Prisma.XOR<Prisma.TelemetryCreateInput, Prisma.TelemetryUncheckedCreateInput>
}

/**
 * Telemetry createMany
 */
export type TelemetryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Telemetries.
   */
  data: Prisma.TelemetryCreateManyInput | Prisma.TelemetryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Telemetry createManyAndReturn
 */
export type TelemetryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * The data used to create many Telemetries.
   */
  data: Prisma.TelemetryCreateManyInput | Prisma.TelemetryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Telemetry update
 */
export type TelemetryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * The data needed to update a Telemetry.
   */
  data: Prisma.XOR<Prisma.TelemetryUpdateInput, Prisma.TelemetryUncheckedUpdateInput>
  /**
   * Choose, which Telemetry to update.
   */
  where: Prisma.TelemetryWhereUniqueInput
}

/**
 * Telemetry updateMany
 */
export type TelemetryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Telemetries.
   */
  data: Prisma.XOR<Prisma.TelemetryUpdateManyMutationInput, Prisma.TelemetryUncheckedUpdateManyInput>
  /**
   * Filter which Telemetries to update
   */
  where?: Prisma.TelemetryWhereInput
  /**
   * Limit how many Telemetries to update.
   */
  limit?: number
}

/**
 * Telemetry updateManyAndReturn
 */
export type TelemetryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * The data used to update Telemetries.
   */
  data: Prisma.XOR<Prisma.TelemetryUpdateManyMutationInput, Prisma.TelemetryUncheckedUpdateManyInput>
  /**
   * Filter which Telemetries to update
   */
  where?: Prisma.TelemetryWhereInput
  /**
   * Limit how many Telemetries to update.
   */
  limit?: number
}

/**
 * Telemetry upsert
 */
export type TelemetryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * The filter to search for the Telemetry to update in case it exists.
   */
  where: Prisma.TelemetryWhereUniqueInput
  /**
   * In case the Telemetry found by the `where` argument doesn't exist, create a new Telemetry with this data.
   */
  create: Prisma.XOR<Prisma.TelemetryCreateInput, Prisma.TelemetryUncheckedCreateInput>
  /**
   * In case the Telemetry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TelemetryUpdateInput, Prisma.TelemetryUncheckedUpdateInput>
}

/**
 * Telemetry delete
 */
export type TelemetryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
  /**
   * Filter which Telemetry to delete.
   */
  where: Prisma.TelemetryWhereUniqueInput
}

/**
 * Telemetry deleteMany
 */
export type TelemetryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Telemetries to delete
   */
  where?: Prisma.TelemetryWhereInput
  /**
   * Limit how many Telemetries to delete.
   */
  limit?: number
}

/**
 * Telemetry without action
 */
export type TelemetryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Telemetry
   */
  select?: Prisma.TelemetrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Telemetry
   */
  omit?: Prisma.TelemetryOmit<ExtArgs> | null
}
